---
- hosts: 172.17.16.251
  become: yes
  become_user: root
  vars_files:
    - roles/common/vars/main.yml
  roles:
    - role: geerlingguy.mysql
    - role: ome.mysql_backup
      mysql_backup_dir: /var/backups/database
      mysql_backup_filename_format: "backup_databases -%Y%m%d.mysqldump"
      mysql_backup_minimum_expected_size: 100000