---
- name: mysql backup | create backup directory
  become: yes
  file:
    path: "/var/backups/database"
    recurse: yes
    state: directory

- name: mysql backup | create cron job
  become: yes
  template:
    src: etc-crond-mysql-backup.j2
    dest: /etc/cron.30/mysql-backup
    mode: 0755
