---
- name: Add a line to hosts file
  lineinfile:
    path: /etc/hosts
    insertafter: '^127.0.0.1 localhost'
    line: 172.16.203.135 srv_master
    line: 192.168.80.136 srv_master
    line: 172.16.203.59 srv_dbslave
    line: 192.168.247.129 srv_dbslave
