---
- name: Ensure group "itesciadm" exists
  group:
    name: itesciadm
    gid: 1001
    state: present

- name: Add the user 'itesciadmin' with a home, a specific uid, groups, password not set and a ssh authorized key.
  user: 
    name: itesciadmin
    home: /home/itesciadmin
    uid: 1001
    group: itesciadm
    groups: itescia,sudo
    password: no
    state: present

- name: Set authorized key, removing all the authorized keys already set
  authorized_key:
    user: root
    key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDAfCo4RCJH8ao5VUYVbTz964GxAb5jwoUR6+ka/Jx+RyE9he3cbBtjQrPKE6Z/ftqy5YyZusg0uHnYz/8kwB/NLTKBg61jJFjn+gR5I0bRYRJQDYRjeR84ERIyP2In/OEerpzK7VEIshTydEzVoOJVZBixo7C33v7f7ZCBIofmyWR/BkyW680nQS4BkERt2UC3enlH80XRXMRbFV2aCz0364qUQpvRZdllCxZTpFja7Mbxu6AIW/IIc0hOOAuvj2eMGK/aUlZn/x1PUI/JHjkzTI+dtZlAv2mkPIY6LDWaRGbZGZJtyhXusuhV3liN8am3ZkTtvy2JFgbFIf811Ffv itescia@anthonyubuntu3'
    state: present
    exclusive: True

