---
- clients:
  - username: client1
    passwd: client1PWD
    url: www.client1.com
  - username: client2
    passwd: client2PWD
    url: www.client2.com
  - username: client3
    passwd: client3PWD
    url: www.client3.com

#mysql_root_password: super-secure-password
#mysql_databases:
#  - name: client1
#    encoding: latin1
#    collation: latin1_general_ci
#  - name: client2
#    encoding: latin1
#    collation: latin1_general_ci
#  - name: client3
#    encoding: latin1
#    collation: latin1_general_ci
#mysql_users:
#  - name: "{{username}}"
#    password: "{{passwd}}"
#    url: "{{url}}"
#loop: "{{clients}}"

